server:
  port: 8081

#management:
#          port: 52092
#          security:
#            enabled: false
#
#info:
#        app:
#              name: "@project.name@" #从pom.xml中获取
#              description: "@project.description@"
#              version: "@project.version@"
#              parent-version: "@project.parent.version@"
#
#spring:
#    profiles:
#       active: '@env@'
#    aop:
#      proxy-target-class: true
#
#    application:
#       name: service-crawler
#
#springfox:
#  documentation:
#    swagger:
#      v2:
#        path: /api-docs
#
#endpoints:
#  shutdown:
#    enabled: true
#    sensitive: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://*****:*****/eureka
spring:
  application:
    name: springboot